---
title: "Chapter 2"
format: html
echo: true
---
```{r}
#| echo: false
#| message: false
library(tidyverse)
library(gcookbook)
```

## Create a scatter plot
### Base R
```{r}
plot(mtcars$wt,mtcars$mpg)
```
### ggplot2
```{r}
ggplot(mtcars, aes(x=wt,y=mpg))+geom_point()
```

## Create a Line graph
### Base R
```{r}
plot(pressure$temperature,pressure$pressure,type="l")
points(pressure$temperature,pressure$pressure)

plot(pressure$temperature,pressure$pressure/2,type="l",col="red")
points(pressure$temperature,pressure$pressure/2,col="red")
```
### ggplot2
```{r}
ggplot(pressure,aes(x=temperature, y=pressure))+geom_line()+geom_point()
```

## Create a Bar Graph
### Base R
```{r}
barplot(BOD$demand,names.arg=BOD$Time)

barplot(table(mtcars$cyl))

```
### ggplot2
```{r}
#values
ggplot(BOD,aes(y=demand,x=Time))+geom_col()

ggplot(BOD, aes(x=factor(Time),y=demand))+geom_col()

#counts
ggplot(mtcars,aes(x=cyl))+geom_bar()

ggplot(mtcars,aes(x=factor(cyl)))+geom_bar()

```

## Creating a histogram
### Base R
```{r}
hist(mtcars$mpg)
```
### ggplot2
```{r}
ggplot(mtcars,aes(x=mpg))+geom_histogram()
ggplot(mtcars,aes(x=mpg))+geom_histogram(binwidth=4)
```

## Creating a box plot
### Base R
```{r}
plot(ToothGrowth$supp,ToothGrowth$len)

boxplot(len ~ supp,data=ToothGrowth)
boxplot(len ~ supp+dose,data=ToothGrowth)
```
### ggplot2
```{r}
ggplot(ToothGrowth,aes(x=supp,y=len))+geom_boxplot()

ggplot(ToothGrowth,aes(x=interaction(supp,dose),y=len))+geom_boxplot()
```

## Plotting a Function Curve
### Base R
```{r}
curve(x^3-5*x,from=-4,to=4)

myfun<-function(xvar){
  1/(1+exp(-xvar+10))
}

curve(myfun(x),from=0,to=20)
curve(1-myfun(x),add=TRUE,col="red")
```
### ggplot2
```{r}
ggplot(data.frame(x=c(0,20)),aes(x=x))+stat_function(fun=myfun,geom="line")
```

