---
title: "Chapter 3 Bar Graphs"
format: html
editor: visual
---
## Basic Bar Graph
### Non-numeric
```{r}
library(gcookbook)
library(tidyverse)
pg_mean
ggplot(pg_mean,aes(x=group,y=weight))+geom_col()
```
### With Numerical categories vs converting to factor
```{r}
ggplot(BOD, aes(x=Time,y=demand))+geom_col()

ggplot(BOD, aes(x=factor(Time),y=demand))+geom_col()
```
### Fill and color
```{r}
ggplot(pg_mean,aes(x=group,y=weight))+geom_col(fill="lightblue",color="black")
```

## Grouping Bars Together
```{r}
cabbage_exp
ggplot(cabbage_exp,aes(x=Date,y=Weight, fill=Cultivar))+geom_col(position="dodge")

ggplot(cabbage_exp, aes(x=Date,y=Weight,fill=Cultivar))+geom_col(position="dodge",color="black")+scale_fill_brewer(palette="Pastel1")
```
## Bar Graph of Counts
```{r}
ggplot(diamonds,aes(x=cut))+geom_bar()
```

## Using Colors in a Bar graph
```{r}
upc<-uspopchange%>% arrange(desc(Change))%>% slice(1:10)
ggplot(upc, aes(x=reorder(Abb,Change),y=Change,fill=Region))+geom_col(color="black")+scale_fill_manual(values=c("#669922","#FFCC66"))+xlab("State")
```

## Coloring Negative and Positive Bars Differently
```{r}
climate_sub<-climate%>% filter(Source=="Berkeley"& Year>=1900)%>%
  mutate(pos=Anomaly10y>=0)
ggplot(climate_sub,aes(x=Year,y=Anomaly10y,fill=pos))+geom_col()

#Better Verison
ggplot(climate_sub,aes(x=Year,y=Anomaly10y,fill=pos))+geom_col(position="identity",color="black", size=.25)+scale_fill_manual(values=c("#CCEEFF","#FFDDDD"),guide="none")

```

## Adjusting Bar Width and Spacing
```{r}
#Non-grouped
ggplot(pg_mean,aes(x=group,y=weight))+geom_col()
ggplot(pg_mean,aes(x=group,y=weight))+geom_col(width=.5)
ggplot(pg_mean,aes(x=group,y=weight))+geom_col(width=1)

#grouped
#narrow bars
ggplot(cabbage_exp,aes(x=Date,y=Weight,fill=Cultivar))+geom_col(width=.5,position="dodge")
#space between bars
ggplot(cabbage_exp,aes(x=Date,y=Weight,fill=Cultivar))+geom_col(width=.5,position=position_dodge(.7))
```

## Making a Stacked Bar Graph
```{r}
ggplot(cabbage_exp,aes(x=Date,y=Weight,fill=Cultivar))+geom_col()+guides(fill=guide_legend(reverse=TRUE))


ggplot(cabbage_exp,aes(x=Date,y=Weight,fill=Cultivar))+geom_col(position=position_stack(reverse = TRUE))+guides(fill=guide_legend(reverse=TRUE))
```

## Making a proprtional stacked bar graph
```{r}
#position=fill to scale proprtionally
ggplot(cabbage_exp,aes(x=Date,y=Weight,fill=Cultivar))+geom_col(position="fill")
#print labels as percentages
ggplot(cabbage_exp,aes(x=Date,y=Weight,fill=Cultivar))+geom_col(position="fill")+scale_y_continuous(labels=scales::percent)
```

## Adding Labels to a Bar Graph
```{r}
ggplot(cabbage_exp,aes(x=interaction(Date,Cultivar),y=Weight))+geom_col()+geom_text(aes(label=Weight),vjust=1.5,color="white")

ggplot(cabbage_exp,aes(x=interaction(Date,Cultivar),y=Weight))+geom_col()+geom_text(aes(label=Weight),vjust=-.2)


#Count labels instead
ggplot(mtcars,aes(x=factor(cyl)))+geom_bar()+geom_text(aes(label=..count..),stat="count",vjust=1.5,color="white")
```
## Cleveland Dot Plot
```{r}
tophit<-tophitters2001[1:25,]
ggplot(tophit,aes(x=avg,y=name))+geom_point()

ggplot(tophit, aes(x=avg,y=reorder(name,avg)))+geom_point(size=3)+
  theme_bw()+
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_line(color="grey60",linetype="dashed"))


nameorder<-tophit$name[order(tophit$lg,tophit$avg)]
tophit$name<-factor(tophit$name,levels=nameorder)
ggplot(tophit,aes(x=avg,y=name))+
  geom_segment(aes(yend=name),xend=0,color="grey50")+
  geom_point(size=3,aes(color=lg))+
  scale_color_brewer(palette="Set1",limits=c("NL","AL"))+
  theme_bw()+
  theme(
    panel.grid.major.y = element_blank(),
    legend.position = c(1,.55),
    legend.justification = c(1,.5)
  )
```

